## Student Attendance Analytics with Pandas

In [52]:
import pandas as pd
import numpy as np

#### Section 0: Data Loading

In [53]:
df = pd.read_excel("attendance.xlsx")
df

,Roll No,Student Name,Subject,Total Classes,Present,Absent,Excused,Attendance %,Status,Classes Needed (75%),Last Present Date,Consecutive Absences
0,4MW23CS121,ROHITH RAO,Data Science & GenAI - 3nd Yr - CSE - A,11,7,4,0,64%,Critical,5 more,2026-10-08,0
1,4MW23CS165,SUDHARSHAN BHARGAV JOSHI,Data Science & GenAI - 3nd Yr - CSE - A,11,0,11,0,0%,Critical,33 more,Never,11
2,4MW24CS001,A S ANUPAMA,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0,83%,Warning,✓ Met,2026-10-08,0
3,4MW24CS002,ABHIJNA SHETTY,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0,100%,Safe,✓ Met,2026-10-08,0
4,4MW24CS003,ABHISHEK,Data Science & GenAI - 3nd Yr - CSE - A,12,6,6,0,50%,Critical,12 more,2026-10-08,0
...,...,...,...,...,...,...,...,...,...,...,...,...
60,4MW24CS059,KARTHIK B NAYAK,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0,83%,Warning,✓ Met,2026-10-05,1
61,4MW24CS060,KAVYA,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0,83%,Warning,✓ Met,2026-10-08,0
62,4MW25CS400,ANAGHA K Y,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0,83%,Warning,✓ Met,2026-10-05,1
63,4MW25CS402,ANVITHA B A,Data Science & GenAI - 3nd Yr - CSE - A,12,11,1,0,92%,Safe,✓ Met,2026-10-08,0
64,4MW25CS403,M NIRANJAN PRABHU,Data Science & GenAI - 3nd Yr - CSE - A,12,3,9,0,25%,Critical,24 more,2026-09-07,9

#### Section 1: Data Inspection

In [54]:
"""Q1. Display the first 10 rows, the shape of the DataFrame, and the data types of each column."""
#-----------------------------Write Solution Code-----------------------------

print("First 10 rows:")
display(df.head(10))
print("DataFrame shape:", df.shape)
print("Column data types:")
display(df.dtypes)

First 10 rows:

,Roll No,Student Name,Subject,Total Classes,Present,Absent,Excused,Attendance %,Status,Classes Needed (75%),Last Present Date,Consecutive Absences
0,4MW23CS121,ROHITH RAO,Data Science & GenAI - 3nd Yr - CSE - A,11,7,4,0,64%,Critical,5 more,2026-10-08,0
1,4MW23CS165,SUDHARSHAN BHARGAV JOSHI,Data Science & GenAI - 3nd Yr - CSE - A,11,0,11,0,0%,Critical,33 more,Never,11
2,4MW24CS001,A S ANUPAMA,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0,83%,Warning,✓ Met,2026-10-08,0
3,4MW24CS002,ABHIJNA SHETTY,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0,100%,Safe,✓ Met,2026-10-08,0
4,4MW24CS003,ABHISHEK,Data Science & GenAI - 3nd Yr - CSE - A,12,6,6,0,50%,Critical,12 more,2026-10-08,0
5,4MW24CS004,ADITHYA A SALIAN,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0,83%,Warning,✓ Met,2026-10-08,0
6,4MW24CS005,AKANKSHA G SHETTY,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0,83%,Warning,✓ Met,2026-10-08,0
7,4MW24CS006,AMULYA B KULAL,Data Science & GenAI - 3nd Yr - CSE - A,12,9,3,0,75%,Warning,✓ Met,2026-10-08,0
8,4MW24CS007,ANANYA,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0,100%,Safe,✓ Met,2026-10-08,0
9,4MW24CS008,ANANYA B,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0,100%,Safe,✓ Met,2026-10-08,0

DataFrame shape: (65, 12)
Column data types:

Roll No                   str
Student Name              str
Subject                   str
Total Classes           int64
Present                 int64
Absent                  int64
Excused                 int64
Attendance %              str
Status                    str
Classes Needed (75%)      str
Last Present Date         str
Consecutive Absences    int64
dtype: object

In [55]:
"""Q2. Check for missing values in each column. Identify which columns have null values (especially Last Present Date with "Never") and report the count. """
#-----------------------------Write Solution Code-----------------------------

df['Last Present Date'] = df['Last Present Date'].replace('Never', pd.NA)
missing_counts = df.isna().sum()
print("Missing values by column:")
display(missing_counts)
print("Columns with missing values:")
display(missing_counts[missing_counts > 0])

Missing values by column:

Roll No                 0
Student Name            0
Subject                 0
Total Classes           0
Present                 0
Absent                  0
Excused                 0
Attendance %            0
Status                  0
Classes Needed (75%)    0
Last Present Date       3
Consecutive Absences    0
dtype: int64

Columns with missing values:

Last Present Date    3
dtype: int64

In [56]:
"""Q3. Rename the columns to snake_case (e.g., Roll No → roll_no, Student Name → student_name, Attendance % → attendance_pct). Display the updated column list."""

#-----------------------------Write Solution Code-----------------------------
df = df.rename(columns={
    'Roll No': 'roll_no',
    'Student Name': 'student_name',
    'Subject': 'subject',
    'Total Classes': 'total_classes',
    'Present': 'present',
    'Absent': 'absent',
    'Excused': 'excused',
    'Attendance %': 'attendance_pct',
    'Status': 'status',
    'Classes Needed (75%)': 'classes_needed_75_pct',
    'Last Present Date': 'last_present_date',
    'Consecutive Absences': 'consecutive_absences'
})
print("Updated columns:")
display(df.columns.tolist())

Updated columns:

['roll_no',
 'student_name',
 'subject',
 'total_classes',
 'present',
 'absent',
 'excused',
 'attendance_pct',
 'status',
 'classes_needed_75_pct',
 'last_present_date',
 'consecutive_absences']

In [57]:
"""Q4. Convert Attendance % from string format (e.g., "64%") to a numeric float column (0.64 or 64.0). Also convert Last Present Date to datetime, handling "Never" as NaT."""
#-----------------------------Write Solution Code-----------------------------
df['attendance_pct'] = pd.to_numeric(
    df['attendance_pct'].astype(str).str.rstrip('%'), errors='coerce'
)
df['last_present_date'] = pd.to_datetime(df['last_present_date'], errors='coerce')
display(df[['attendance_pct', 'last_present_date']].head())

   attendance_pct last_present_date
0              64        2026-10-08
1               0               NaT
2              83        2026-10-08
3             100        2026-10-08
4              50        2026-10-08

#### Section 2: Filtering & Selection

In [58]:
"""Q5. Filter and display all students whose Status is "Critical". Sort them by Attendance % in ascending order."""
#-----------------------------Write Solution Code-----------------------------
critical_students = df.loc[df['status'].eq('Critical')].sort_values('attendance_pct')
display(critical_students)

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75_pct,last_present_date,consecutive_absences
1,4MW23CS165,SUDHARSHAN BHARGAV JOSHI,Data Science & GenAI - 3nd Yr - CSE - A,11,0,11,0,0,Critical,33 more,NaT,11
21,4MW24CS020,ARON OWEN D'SOUZA,Data Science & GenAI - 3nd Yr - CSE - A,12,0,12,0,0,Critical,36 more,NaT,12
51,4MW24CS050,GAUTHAM G PRABHU,Data Science & GenAI - 3nd Yr - CSE - A,12,0,12,0,0,Critical,36 more,NaT,12
35,4MW24CS034,DARREN DSOUZA,Data Science & GenAI - 3nd Yr - CSE - A,12,1,11,0,8,Critical,32 more,2026-08-31,11
59,4MW24CS058,JEETHAN WELROY FERNANDES,Data Science & GenAI - 3nd Yr - CSE - A,12,1,11,0,8,Critical,32 more,2026-08-31,11
42,4MW24CS041,DHIKSHITH AITHAL KG,Data Science & GenAI - 3nd Yr - CSE - A,12,2,10,0,17,Critical,28 more,2026-09-07,9
47,4MW24CS046,DRUSHYA K SHETTY,Data Science & GenAI - 3nd Yr - CSE - A,12,2,10,0,17,Critical,28 more,2026-10-08,0
64,4MW25CS403,M NIRANJAN PRABHU,Data Science & GenAI - 3nd Yr - CSE - A,12,3,9,0,25,Critical,24 more,2026-09-07,9
20,4MW24CS019,ANVESH N ACHARYA,Data Science & GenAI - 3nd Yr - CSE - A,12,5,7,0,42,Critical,16 more,2026-09-21,6
57,4MW24CS056,HIMESH PRAKASH NAIK,Data Science & GenAI - 3nd Yr - CSE - A,12,6,6,0,50,Critical,12 more,2026-09-28,3
4,4MW24CS003,ABHISHEK,Data Science & GenAI - 3nd Yr - CSE - A,12,6,6,0,50,Critical,12 more,2026-10-08,0
22,4MW24CS021,ARUNA,Data Science & GenAI - 3nd Yr - CSE - A,12,6,6,0,50,Critical,12 more,2026-10-05,1
58,4MW24CS057,JATIN NAGESH NAIK,Data Science & GenAI - 3nd Yr - CSE - A,12,6,6,0,50,Critical,12 more,2026-10-05,1
55,4MW24CS054,HARSHA S RAO,Data Science & GenAI - 3nd Yr - CSE - A,12,7,5,0,58,Critical,8 more,2026-10-08,0
52,4MW24CS051,GOWRISH M SHEREGARA,Data Science & GenAI - 3nd Yr - CSE - A,12,7,5,0,58,Critical,8 more,2026-10-08,0
38,4MW24CS037,DEVADIGA SUHAS SURESH,Data Science & GenAI - 3nd Yr - CSE - A,12,7,5,0,58,Critical,8 more,2026-10-08,0
0,4MW23CS121,ROHITH RAO,Data Science & GenAI - 3nd Yr - CSE - A,11,7,4,0,64,Critical,5 more,2026-10-08,0
27,4MW24CS026,ATHMIK Y ACHARYA,Data Science & GenAI - 3nd Yr - CSE - A,12,8,4,0,67,Critical,4 more,2026-10-05,1
49,4MW24CS048,GANAVI SUSHMA,Data Science & GenAI - 3nd Yr - CSE - A,12,8,4,0,67,Critical,4 more,2026-10-08,0

In [59]:
"""Q6. Extract all students who have 0 present days (fully absent). List their roll numbers, names, and consecutive absences."""
#-----------------------------Write Solution Code-----------------------------
fully_absent = df.loc[df['present'].eq(0), ['roll_no', 'student_name', 'consecutive_absences']]
display(fully_absent)

       roll_no              student_name  consecutive_absences
1   4MW23CS165  SUDHARSHAN BHARGAV JOSHI                    11
21  4MW24CS020         ARON OWEN D'SOUZA                    12
51  4MW24CS050          GAUTHAM G PRABHU                    12

In [60]:
"""Q7. Using .loc and .iloc, display:
(a) All "Safe" students using .loc
(b) The first 15 rows and columns 2-6 using .iloc """
#-----------------------------Write Solution Code-----------------------------
print("Safe students (.loc):")
display(df.loc[df['status'].eq('Safe')])
print("First 15 rows, columns at positions 2 through 6 (.iloc):")
display(df.iloc[:15, 2:7])

Safe students (.loc):

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75_pct,last_present_date,consecutive_absences
3,4MW24CS002,ABHIJNA SHETTY,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0,100,Safe,✓ Met,2026-10-08,0
8,4MW24CS007,ANANYA,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0,100,Safe,✓ Met,2026-10-08,0
9,4MW24CS008,ANANYA B,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0,100,Safe,✓ Met,2026-10-08,0
12,4MW24CS011,ANANYA Y BANGERA,Data Science & GenAI - 3nd Yr - CSE - A,12,11,1,0,92,Safe,✓ Met,2026-10-08,0
14,4MW24CS013,ANKITHA,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0,100,Safe,✓ Met,2026-10-08,0
15,4MW24CS014,ANULEKHA NAIK,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0,100,Safe,✓ Met,2026-10-08,0
18,4MW24CS017,ANUSHREE K,Data Science & GenAI - 3nd Yr - CSE - A,12,11,1,0,92,Safe,✓ Met,2026-10-08,0
23,4MW24CS022,ARYA ASWEEN DESAI,Data Science & GenAI - 3nd Yr - CSE - A,12,11,1,0,92,Safe,✓ Met,2026-10-08,0
25,4MW24CS024,ASHISH,Data Science & GenAI - 3nd Yr - CSE - A,12,11,1,0,92,Safe,✓ Met,2026-10-08,0
26,4MW24CS025,ASHRAYA SHETTY,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0,100,Safe,✓ Met,2026-10-08,0
28,4MW24CS027,AVISHA,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0,100,Safe,✓ Met,2026-10-08,0
30,4MW24CS029,BHOOMIKA,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0,100,Safe,✓ Met,2026-10-08,0
31,4MW24CS030,CHANDANA,Data Science & GenAI - 3nd Yr - CSE - A,12,11,1,0,92,Safe,✓ Met,2026-10-08,0
33,4MW24CS032,CLEONIE,Data Science & GenAI - 3nd Yr - CSE - A,12,11,1,0,92,Safe,✓ Met,2026-10-08,0
36,4MW24CS035,DEEKSHITH,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0,100,Safe,✓ Met,2026-10-08,0
41,4MW24CS040,DHANYATHA S MADDODI,Data Science & GenAI - 3nd Yr - CSE - A,12,11,1,0,92,Safe,✓ Met,2026-10-08,0
44,4MW24CS043,DISHA (PRAKASH BANGERA),Data Science & GenAI - 3nd Yr - CSE - A,12,11,1,0,92,Safe,✓ Met,2026-10-08,0
48,4MW24CS047,GANAPATHI MALLYA,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0,100,Safe,✓ Met,2026-10-08,0
56,4MW24CS055,HIMANI,Data Science & GenAI - 3nd Yr - CSE - A,12,11,1,0,92,Safe,✓ Met,2026-10-08,0
63,4MW25CS402,ANVITHA B A,Data Science & GenAI - 3nd Yr - CSE - A,12,11,1,0,92,Safe,✓ Met,2026-10-08,0

First 15 rows, columns at positions 2 through 6 (.iloc):

,subject,total_classes,present,absent,excused
0,Data Science & GenAI - 3nd Yr - CSE - A,11,7,4,0
1,Data Science & GenAI - 3nd Yr - CSE - A,11,0,11,0
2,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0
3,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0
4,Data Science & GenAI - 3nd Yr - CSE - A,12,6,6,0
5,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0
6,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0
7,Data Science & GenAI - 3nd Yr - CSE - A,12,9,3,0
8,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0
9,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0
10,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0
11,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0
12,Data Science & GenAI - 3nd Yr - CSE - A,12,11,1,0
13,Data Science & GenAI - 3nd Yr - CSE - A,12,9,3,0
14,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0

In [61]:
"""Q8. Find all students whose Consecutive Absences is greater than or equal to 5. Display their name, status, and last present date."""
#-----------------------------Write Solution Code-----------------------------
high_absence_streaks = df.loc[
    df['consecutive_absences'].ge(5),
    ['student_name', 'status', 'last_present_date']
]
display(high_absence_streaks)

                student_name    status last_present_date
1   SUDHARSHAN BHARGAV JOSHI  Critical               NaT
20          ANVESH N ACHARYA  Critical        2026-09-21
21         ARON OWEN D'SOUZA  Critical               NaT
35             DARREN DSOUZA  Critical        2026-08-31
42       DHIKSHITH AITHAL KG  Critical        2026-09-07
51          GAUTHAM G PRABHU  Critical               NaT
59  JEETHAN WELROY FERNANDES  Critical        2026-08-31
64         M NIRANJAN PRABHU  Critical        2026-09-07

### Section 3: Grouping & Aggregation

In [62]:
"""Q9. Group the data by Status and compute: 
a) Count of students 
b) Average attendance %  
c) Maximum consecutive absences"""
#-----------------------------Write Solution Code-----------------------------
status_summary = df.groupby('status').agg(
    student_count=('roll_no', 'count'),
    average_attendance_pct=('attendance_pct', 'mean'),
    max_consecutive_absences=('consecutive_absences', 'max')
)
display(status_summary)

          student_count  average_attendance_pct  max_consecutive_absences
status
Critical             19               36.263158                        12
Safe                 20               96.000000                         0
Warning              26               80.500000                         1

In [63]:
"""Q10. Create a new column Attendance Category:
≥ 90% → "Excellent"
75-89% → "Good"
60-74% → "Average"
< 60% → "Poor"
Then use groupby() to count students in each category."""
#-----------------------------Write Solution Code-----------------------------
df['attendance_category'] = np.select(
    [
        df['attendance_pct'].ge(90),
        df['attendance_pct'].ge(75),
        df['attendance_pct'].ge(60)
    ],
    ['Excellent', 'Good', 'Average'],
    default='Poor'
)
category_counts = df.groupby('attendance_category').size().rename('student_count')
display(category_counts)

attendance_category
Average       3
Excellent    20
Good         26
Poor         16
Name: student_count, dtype: int64

In [64]:
"""Q11. Calculate the total number of classes conducted (sum of Total Classes) and the total present/absent counts across all students using .agg()."""
#-----------------------------Write Solution Code-----------------------------
totals = df[['total_classes', 'present', 'absent']].agg('sum')
display(totals)

total_classes    777
present          563
absent           214
dtype: int64

In [65]:
"""Q12. Group by Status and use .agg() to find:
a)min, max, and mean of Present
b)sum of Absent"""
#-----------------------------Write Solution Code-----------------------------
present_absent_by_status = df.groupby('status').agg({
    'present': ['min', 'max', 'mean'],
    'absent': 'sum'
})
display(present_absent_by_status)

         present                absent
             min max       mean    sum
status
Critical       0   8   4.315789    144
Safe          11  12  11.500000     10
Warning        9  10   9.653846     60

### Section 4: Feature Engineering & Transformation

In [66]:
"""Q13. Create a new column Risk Score using the formula:
Risk Score = (Absent * 0.4) + (Consecutive Absences * 0.6)
Display the top 10 students with the highest risk score."""
#-----------------------------Write Solution Code-----------------------------
df['risk_score'] = (df['absent'] * 0.4) + (df['consecutive_absences'] * 0.6)
top_10_risk = df.nlargest(10, 'risk_score')[['roll_no', 'student_name', 'risk_score']]
display(top_10_risk)

       roll_no              student_name  risk_score
21  4MW24CS020         ARON OWEN D'SOUZA        12.0
51  4MW24CS050          GAUTHAM G PRABHU        12.0
1   4MW23CS165  SUDHARSHAN BHARGAV JOSHI        11.0
35  4MW24CS034             DARREN DSOUZA        11.0
59  4MW24CS058  JEETHAN WELROY FERNANDES        11.0
42  4MW24CS041       DHIKSHITH AITHAL KG         9.4
64  4MW25CS403         M NIRANJAN PRABHU         9.0
20  4MW24CS019          ANVESH N ACHARYA         6.4
57  4MW24CS056       HIMESH PRAKASH NAIK         4.2
47  4MW24CS046          DRUSHYA K SHETTY         4.0

In [67]:
"""Q14. Add a column Classes Needed (Numeric) by extracting the numeric value from the Classes Needed (75%) column (e.g., "5 more" → 5, "✓ Met" → 0)."""
#-----------------------------Write Solution Code-----------------------------
df['classes_needed_numeric'] = (
    df['classes_needed_75_pct'].astype(str).str.extract(r'(\d+)')[0]
    .fillna('0').astype(int)
)
display(df[['classes_needed_75_pct', 'classes_needed_numeric']].head(10))

  classes_needed_75_pct  classes_needed_numeric
0                5 more                       5
1               33 more                      33
2                 ✓ Met                       0
3                 ✓ Met                       0
4               12 more                      12
5                 ✓ Met                       0
6                 ✓ Met                       0
7                 ✓ Met                       0
8                 ✓ Met                       0
9                 ✓ Met                       0

In [68]:
"""Q15. Using apply() with a lambda function, create a column Attendance Flag that returns:
a)"Defaulter" if attendance < 75%
b)"Safe" otherwise """
#-----------------------------Write Solution Code-----------------------------
df['attendance_flag'] = df['attendance_pct'].apply(
    lambda attendance: 'Defaulter' if attendance < 75 else 'Safe'
)
display(df[['student_name', 'attendance_pct', 'attendance_flag']].head(10))

               student_name  attendance_pct attendance_flag
0                ROHITH RAO              64       Defaulter
1  SUDHARSHAN BHARGAV JOSHI               0       Defaulter
2               A S ANUPAMA              83            Safe
3            ABHIJNA SHETTY             100            Safe
4                  ABHISHEK              50       Defaulter
5          ADITHYA A SALIAN              83            Safe
6         AKANKSHA G SHETTY              83            Safe
7            AMULYA B KULAL              75            Safe
8                    ANANYA             100            Safe
9                  ANANYA B             100            Safe

In [69]:
"""Q16. Use pd.cut() to bin students into attendance ranges: [0-50, 50-75, 75-90, 90-100] and label them as ["Critical", "Warning", "Good", "Excellent"]."""
#-----------------------------Write Solution Code-----------------------------
df['attendance_range'] = pd.cut(
    df['attendance_pct'],
    bins=[0, 50, 75, 90, np.inf],
    labels=['Critical', 'Warning', 'Good', 'Excellent'],
    right=False
)
display(df[['student_name', 'attendance_pct', 'attendance_range']].head(10))

               student_name  attendance_pct attendance_range
0                ROHITH RAO              64          Warning
1  SUDHARSHAN BHARGAV JOSHI               0         Critical
2               A S ANUPAMA              83             Good
3            ABHIJNA SHETTY             100        Excellent
4                  ABHISHEK              50          Warning
5          ADITHYA A SALIAN              83             Good
6         AKANKSHA G SHETTY              83             Good
7            AMULYA B KULAL              75             Good
8                    ANANYA             100        Excellent
9                  ANANYA B             100        Excellent

### Section 5: Advanced Analysis

In [70]:
"""Q17. Using pivot_table(), create a summary showing the count of students by Status and Attendance Category (created in Q10)."""
#-----------------------------Write Solution Code-----------------------------
status_category_summary = pd.pivot_table(
    df,
    index='status',
    columns='attendance_category',
    values='roll_no',
    aggfunc='count',
    fill_value=0
)
display(status_category_summary)

attendance_category  Average  Excellent  Good  Poor
status
Critical                   3          0     0    16
Safe                       0         20     0     0
Warning                    0          0    26     0

In [71]:
"""Q18. Identify duplicate student names (e.g., "ANANYA", "DISHA") and display all rows where the base name repeats. Use string manipulation to extract the base name."""
#-----------------------------Write Solution Code-----------------------------
df['base_name'] = df['student_name'].astype(str).str.extract(r'^([A-Z]{2,})', expand=False)
duplicate_base_names = df['base_name'].notna() & df['base_name'].duplicated(keep=False)
repeated_names = df.loc[duplicate_base_names].sort_values(['base_name', 'student_name'])
display(repeated_names)

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75_pct,last_present_date,consecutive_absences,attendance_category,risk_score,classes_needed_numeric,attendance_flag,attendance_range,base_name
8,4MW24CS007,ANANYA,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0,100,Safe,✓ Met,2026-10-08,0,Excellent,0.0,0,Safe,Excellent,ANANYA
9,4MW24CS008,ANANYA B,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0,100,Safe,✓ Met,2026-10-08,0,Excellent,0.0,0,Safe,Excellent,ANANYA
10,4MW24CS009,ANANYA NAYAK (UMESH NAYAK),Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0,83,Warning,✓ Met,2026-10-08,0,Good,0.8,0,Safe,Good,ANANYA
11,4MW24CS010,ANANYA NAYAK(VEERENDRA KUMAR),Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0,83,Warning,✓ Met,2026-10-08,0,Good,0.8,0,Safe,Good,ANANYA
12,4MW24CS011,ANANYA Y BANGERA,Data Science & GenAI - 3nd Yr - CSE - A,12,11,1,0,92,Safe,✓ Met,2026-10-08,0,Excellent,0.4,0,Safe,Excellent,ANANYA
16,4MW24CS015,ANUSHA,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0,83,Warning,✓ Met,2026-10-08,0,Good,0.8,0,Safe,Good,ANUSHA
17,4MW24CS016,ANUSHA S BHAT,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0,83,Warning,✓ Met,2026-10-08,0,Good,0.8,0,Safe,Good,ANUSHA
18,4MW24CS017,ANUSHREE K,Data Science & GenAI - 3nd Yr - CSE - A,12,11,1,0,92,Safe,✓ Met,2026-10-08,0,Excellent,0.4,0,Safe,Excellent,ANUSHREE
19,4MW24CS018,ANUSHREE P TANTRY,Data Science & GenAI - 3nd Yr - CSE - A,12,9,3,0,75,Warning,✓ Met,2026-10-08,0,Good,1.2,0,Safe,Good,ANUSHREE
44,4MW24CS043,DISHA (PRAKASH BANGERA),Data Science & GenAI - 3nd Yr - CSE - A,12,11,1,0,92,Safe,✓ Met,2026-10-08,0,Excellent,0.4,0,Safe,Excellent,DISHA
45,4MW24CS044,DISHA (UDAY G),Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0,83,Warning,✓ Met,2026-10-05,1,Good,1.4,0,Safe,Good,DISHA
46,4MW24CS045,DISHA S POOJARY,Data Science & GenAI - 3nd Yr - CSE - A,12,9,3,0,75,Warning,✓ Met,2026-10-08,0,Good,1.2,0,Safe,Good,DISHA
50,4MW24CS049,GAUTHAM B K,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0,83,Warning,✓ Met,2026-10-08,0,Good,0.8,0,Safe,Good,GAUTHAM
51,4MW24CS050,GAUTHAM G PRABHU,Data Science & GenAI - 3nd Yr - CSE - A,12,0,12,0,0,Critical,36 more,NaT,12,Poor,12.0,36,Defaulter,Critical,GAUTHAM

In [72]:
""""Q19. Merge this dataset with a hypothetical Student_Details DataFrame containing Roll No, Branch, and Semester. Perform an inner join and display the merged result."""
#-----------------------------Write Solution Code-----------------------------
student_details = df[['roll_no']].drop_duplicates().assign(branch='CSE', semester=5)
merged_students = df.merge(student_details, on='roll_no', how='inner')
display(merged_students)

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75_pct,last_present_date,consecutive_absences,attendance_category,risk_score,classes_needed_numeric,attendance_flag,attendance_range,base_name,branch,semester
0,4MW23CS121,ROHITH RAO,Data Science & GenAI - 3nd Yr - CSE - A,11,7,4,0,64,Critical,5 more,2026-10-08,0,Average,1.6,5,Defaulter,Warning,ROHITH,CSE,5
1,4MW23CS165,SUDHARSHAN BHARGAV JOSHI,Data Science & GenAI - 3nd Yr - CSE - A,11,0,11,0,0,Critical,33 more,NaT,11,Poor,11.0,33,Defaulter,Critical,SUDHARSHAN,CSE,5
2,4MW24CS001,A S ANUPAMA,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0,83,Warning,✓ Met,2026-10-08,0,Good,0.8,0,Safe,Good,NaN,CSE,5
3,4MW24CS002,ABHIJNA SHETTY,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0,100,Safe,✓ Met,2026-10-08,0,Excellent,0.0,0,Safe,Excellent,ABHIJNA,CSE,5
4,4MW24CS003,ABHISHEK,Data Science & GenAI - 3nd Yr - CSE - A,12,6,6,0,50,Critical,12 more,2026-10-08,0,Poor,2.4,12,Defaulter,Warning,ABHISHEK,CSE,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,4MW24CS059,KARTHIK B NAYAK,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0,83,Warning,✓ Met,2026-10-05,1,Good,1.4,0,Safe,Good,KARTHIK,CSE,5
61,4MW24CS060,KAVYA,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0,83,Warning,✓ Met,2026-10-08,0,Good,0.8,0,Safe,Good,KAVYA,CSE,5
62,4MW25CS400,ANAGHA K Y,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0,83,Warning,✓ Met,2026-10-05,1,Good,1.4,0,Safe,Good,ANAGHA,CSE,5
63,4MW25CS402,ANVITHA B A,Data Science & GenAI - 3nd Yr - CSE - A,12,11,1,0,92,Safe,✓ Met,2026-10-08,0,Excellent,0.4,0,Safe,Excellent,ANVITHA,CSE,5
64,4MW25CS403,M NIRANJAN PRABHU,Data Science & GenAI - 3nd Yr - CSE - A,12,3,9,0,25,Critical,24 more,2026-09-07,9,Poor,9.0,24,Defaulter,Critical,NaN,CSE,5

In [73]:
"""Q20. Export the following to separate CSV files:
(a) All "Critical" students
(b) Summary statistics grouped by Status
(c) Top 10 students by Risk Score"""
#-----------------------------Write Solution Code-----------------------------
critical_students.to_csv('critical_students.csv', index=False)
status_summary.to_csv('attendance_summary_by_status.csv')
top_10_risk.to_csv('top_10_students_by_risk_score.csv', index=False)
print("Exported: critical_students.csv, attendance_summary_by_status.csv, top_10_students_by_risk_score.csv")

Exported: critical_students.csv, attendance_summary_by_status.csv, top_10_students_by_risk_score.csv