## Column Transformation

In [2]:
import pandas as pd
import numpy as np

#### Row and Column Selection

In [3]:
sdata=pd.read_csv("Subdata_pandas/student.csv")
sdata

    id firstName  lastName  age  marks   fees
0  101    Akshay    Shetty   20     85  25000
1  102    Ananya       Rao   21     92  30000
2  103     Rohit  Bhandary   19     76  28000
3  104     Nisha   D'Souza   20     88  25000
4  105   Karthik   Poojary   22     69  32000
5  106    Shreya    Shetty   19     95  30000
6  107     Rohan      Naik   21     72  27000
7  108   Deepika      Bhat   20     81  28000
8  109  Abhishek    Kotian   22     64  26000
9  110     Pooja       Rai   19     90  30000

In [4]:
#Selceting a specific column
sdata[['firstName','marks']]
sdata.loc[sdata.firstName=='Rohit']
# sdata.info()
sdata.loc[sdata.marks>=90]
# sdata.loc[:3] #
sdata.iloc[:3,0:3] #Slicing of r and c is only posible in iloc
sdata[['firstName','fees','age']].loc[sdata.marks>=90]

  firstName   fees  age
1    Ananya  30000   21
5    Shreya  30000   19
9     Pooja  30000   19

#### Select student firtname age fees with marks more the 90
#### Select student age >= 20

In [5]:
sdata[['firstName','fees','age']].loc[sdata.marks>=90]
print(sdata['age']>=20)
sdata.loc[sdata.age>=20]
safilter=sdata.loc[sdata.age>=20]

0     True
1     True
2    False
3     True
4     True
5    False
6     True
7     True
8     True
9    False
Name: age, dtype: bool

In [6]:
sdata.where(sdata['age']>=20 ,other="Minor")

      id firstName lastName    age  marks   fees
0    101    Akshay   Shetty     20     85  25000
1    102    Ananya      Rao     21     92  30000
2  Minor     Minor    Minor  Minor  Minor  Minor
3    104     Nisha  D'Souza     20     88  25000
4    105   Karthik  Poojary     22     69  32000
5  Minor     Minor    Minor  Minor  Minor  Minor
6    107     Rohan     Naik     21     72  27000
7    108   Deepika     Bhat     20     81  28000
8    109  Abhishek   Kotian     22     64  26000
9  Minor     Minor    Minor  Minor  Minor  Minor