In [34]:
import pandas as pd
import numpy as np

## Dealing with Duplicate data and Missing value

### Duplicate Data

In [56]:
cdata=pd.read_csv("Subdata_pandas/company.csv")
cdata

    EEID      Name gender   salary
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M      NaN
6  EMP02     rohit      M  25000.0

In [24]:
cdata.duplicated()
#cheack emp id
cdata["EEID"].duplicated()
#cheak Name
cdata["Name"].duplicated()
#Drop data
cdata['EEID'].drop_duplicates()

0    EMP01
1    EMP02
2    EMP03
4    EMP05
5    EMP06
Name: EEID, dtype: str

### Missing Value

In [40]:
cdata.isnull().sum()
#Eliminate null values
cdata.dropna() #Drop all row containg null value

    EEID    Name gender   salary
1  EMP02   rohit      M  25000.0
3  EMP01  ayushi      F  20000.0
6  EMP02   rohit      M  25000.0

#### METHOD 1

In [52]:
#Replace null with any value
cdata.replace(np.nan,"EmptyData")
mean=np.mean(cdata["salary"])
#Replace null in salary column with mean of salary
cdata["salary"].replace(np.nan,mean)

0    24400.0
1    25000.0
2    27000.0
3    20000.0
4    25000.0
5    24400.0
6    25000.0
Name: salary, dtype: float64

#### METHOD 2

In [54]:
cdata['salary']=cdata['salary'].fillna(mean)
cdata

    EEID      Name gender   salary
0  EMP01    ayushi      F  24400.0
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M  24400.0
6  EMP02     rohit      M  25000.0

In [ ]:
cdata=pd.read_csv("Subdata_pandas/company.csv")
print(cdata)
# Forword fill - previous data will be filled
# cdata.ffill()
#Backword fill - next data will be filled
# cdata.bfill()
cdata["salary"]=cdata['salary'].bfill()
cdata

    EEID      Name gender   salary
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M      NaN
6  EMP02     rohit      M  25000.0

    EEID      Name gender   salary
0  EMP01    ayushi      F  25000.0
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M  25000.0
6  EMP02     rohit      M  25000.0